### ISSUE TITLE
Highcharts 

### ISSUE THREAD

**Issue by nicolechung** [webpack-contrib/babili-webpack-plugin#37] opened 2017-04-28 19:02 UTC
I am having an issue with this plugin and Highcharts.

Unfortunately I can't post an error because there is only a warning about a width and height not being set on the parent container (highstock).

Before, with Uglify, I could get the charts working by not mangling the following.
```
new webpack.optimize.UglifyJsPlugin({
   mangle: {
      except: ['highcharts', 'react-highcharts']
   }
})
```

I tried something similar with Babli:

```
new BabiliPlugin({
        mangle: {
          blacklist: ['highcharts', 'react-highcharts']
        }
      })
```

But my charts are not working...I can see and x and y axis but no chart ... instead of a chart line I see a straight line. 

Sorry I realize this probably isn't helpful but other than that warning there is no JavaScript error??

**Comment by boopathi** [comment] 2017-04-30 00:48
Thanks for the report. There are some [debugging tips here](https://github.com/babel/babili/blob/master/CONTRIBUTING.md#debugging) to drill down the error to a small snippet. 

I'm closing this since this is not BabiliPlugin related, but might a bug with Babili itself. Feel free to open an issue in Babili with a reproduce-able snippet.

**Closed by boopathi** 2017-04-30 00:48 UTC
